In [1]:
import pandas as pd
actors = pd.read_csv('/Users/apillai2/Downloads/name.basics.tsv', sep='\t', header=0)

In [2]:
actors.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0031983,tt0072308,tt0050419,tt0053137"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0037382,tt0117057,tt0038355,tt0071877"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0057345,tt0056404,tt0054452,tt0049189"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0072562,tt0080455,tt0078723,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050976,tt0060827,tt0083922,tt0050986"

In [3]:
len(actors)

11359935

In [4]:
actors = actors[(actors.birthYear > '1950') & (actors.primaryProfession.str.contains('act'))]
actors['titleCount'] = actors['knownForTitles'].str.count(',')+1
actors = actors[(actors.titleCount > 4)]
actors = actors.reset_index(drop=True)
print(len(actors))
actors.head()

18

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles,titleCount
0,nm0244191,Peter Durkin,\N,\N,"actor,stunts","tt10360064,tt2951478,tt0159876,tt0179846,tt010...",5
1,nm0300543,Per Gade,\N,\N,"music_department,actor","tt2127538,tt0115588,tt0467490,tt1111774,tt0115374",5
2,nm0472407,Dora Krsková,1978,\N,actress,"tt7174612,tt1024861,tt0356799,tt6368164,tt0117...",6
3,nm10102449,Zachary Iziah Smith,1991,\N,"actor,composer,writer","tt15445360,tt14726796,tt10633130,tt10691474,tt...",5
4,nm10163074,Monika Tyagi,\N,\N,"assistant_director,actress","tt15692286,tt8130558,tt11260832,tt13773882,tt8...",5

In [6]:
actors[actors.primaryName.str.contains('Brad Pitt')]

Empty DataFrame
Columns: [nconst, primaryName, birthYear, deathYear, primaryProfession, knownForTitles, titleCount]
Index: []

In [7]:
actors[actors.primaryName.str.contains('Chris Nolan')]

Empty DataFrame
Columns: [nconst, primaryName, birthYear, deathYear, primaryProfession, knownForTitles, titleCount]
Index: []

In [8]:
allTitles = ['tt0118571']

In [9]:
for i in actors['knownForTitles'].tolist():
    allTitles=allTitles+i.split(',')

In [10]:
uniqTitles = list(set(allTitles))
len(uniqTitles)

93

In [11]:
from bs4 import BeautifulSoup
from selenium import webdriver 
from selenium.webdriver.chrome.options import Options
import re 
import urllib
import time

In [12]:
#create a webdriver object and set options for headless browsing
options = Options()
options.headless = True
driver = webdriver.Chrome('./chromedriver',options=options)
#driver = webdriver.Chrome("/usr/local/bin/chromedriver",options=options)

In [13]:
#uses webdriver object to execute javascript code and get dynamically loaded webcontent
def get_js_soup(url,driver):
    driver.get(url)
    res_html = driver.execute_script('return document.body.innerHTML')
    soup = BeautifulSoup(res_html,'html.parser') #beautiful soup object to be used for parsing html content
    return soup

#tidies extracted text 
def process_bio(bio):
    bio = bio.encode('ascii',errors='ignore').decode('utf-8')       #removes non-ascii characters
    bio = re.sub('\s+',' ',bio)       #repalces repeated whitespace characters with single space
    return bio

''' More tidying
Sometimes the text extracted HTML webpage may contain javascript code and some style elements. 
This function removes script and style tags from HTML so that extracted text does not contain them.
'''
def remove_script(soup):
    for script in soup(["script", "style"]):
        script.decompose()
    return soup


#Checks if bio_url is a valid faculty homepage
def is_valid_homepage(bio_url,dir_url):
    if bio_url.endswith('.pdf'): #we're not parsing pdfs
        return False
    try:
        #sometimes the homepage url points to the same page as the faculty profile page
        #which should be treated differently from an actual homepage
        ret_url = urllib.request.urlopen(bio_url).geturl() 
    except:
        return False       #unable to access bio_url
    urls = [re.sub('((https?://)|(www.))','',url) for url in [ret_url,dir_url]] #removes url scheme (https,http or www) 
    return not(urls[0]== urls[1])

In [14]:
def scrape_faculty_page(fac_url,driver):
    soup = get_js_soup(fac_url,driver)
    homepage_found = False
    bio_url = fac_url
    #profile_sec = soup.find('section',class_='main-content')
    profile_sec = soup.find('section',class_='article listo')
    if profile_sec == None:
        bio = ''
        print("Skipping bio : ",bio_url)
    else:
        bio = process_bio(profile_sec.get_text(separator=' '))
    #print("bio is ",bio_url)
    return bio_url,bio

In [15]:
def write_lst(lst,file_):
    lst = lst.replace(' Plot Showing all 1 items Jump to: Summaries (1)','')
    #lst = lst[6:]
    lst = lst.replace('Edit ','')
    #lst = lst.replace(' Summaries ','\n\nSummaries\n')
    #lst = lst.replace(' Synopsis ','\n\nSynopsis\n')

    with open(file_,'w') as f:
        f.write(lst)

In [16]:
#Scrape homepages of all urls
tot_urls = len(uniqTitles)
for i,l in enumerate(uniqTitles):
    link="https://www.imdb.com/title/"+l+"/plotsummary"
    print ('-'*20,'Scraping faculty url {}/{}'.format(i+1,tot_urls),'-'*20)
    print(link)
    bio_urls, bios = [],[]
    bio_url,bio = scrape_faculty_page(link,driver)
    if bio.strip()!= '' and bio_url.strip()!='':  
        bio_file = '/Users/apillai2/000_CS410_PROJECT/movieFile/'+l+'.txt'
        write_lst(bio,bio_file)
driver.close()

-------------------- Scraping faculty url 1/93 --------------------
https://www.imdb.com/title/tt7525558/plotsummary
-------------------- Scraping faculty url 2/93 --------------------
https://www.imdb.com/title/tt11620836/plotsummary
-------------------- Scraping faculty url 3/93 --------------------
https://www.imdb.com/title/tt0832445/plotsummary
-------------------- Scraping faculty url 4/93 --------------------
https://www.imdb.com/title/tt10690610/plotsummary
-------------------- Scraping faculty url 5/93 --------------------
https://www.imdb.com/title/tt0356799/plotsummary
-------------------- Scraping faculty url 6/93 --------------------
https://www.imdb.com/title/tt5132628/plotsummary
-------------------- Scraping faculty url 7/93 --------------------
https://www.imdb.com/title/tt6661466/plotsummary
-------------------- Scraping faculty url 8/93 --------------------
https://www.imdb.com/title/tt6915926/plotsummary
-------------------- Scraping faculty url 9/93 --------------------
https://www.imdb.com/title/tt14726796/plotsummary
-------------------- Scraping faculty url 10/93 --------------------
https://www.imdb.com/title/tt2280364/plotsummary
-------------------- Scraping faculty url 11/93 --------------------
https://www.imdb.com/title/tt0179846/plotsummary
-------------------- Scraping faculty url 12/93 --------------------
https://www.imdb.com/title/tt8006806/plotsummary
-------------------- Scraping faculty url 13/93 --------------------
https://www.imdb.com/title/tt1111774/plotsummary
-------------------- Scraping faculty url 14/93 --------------------
https://www.imdb.com/title/tt15445360/plotsummary
-------------------- Scraping faculty url 15/93 --------------------
https://www.imdb.com/title/tt2090537/plotsummary
-------------------- Scraping faculty url 16/93 --------------------
https://www.imdb.com/title/tt4114602/plotsummary
-------------------- Scraping faculty url 17/93 --------------------
https://www.imdb.com/title/tt0115374/plotsummary
-------------------- Scraping faculty url 18/93 --------------------
https://www.imdb.com/title/tt10741606/plotsummary
-------------------- Scraping faculty url 19/93 --------------------
https://www.imdb.com/title/tt0118571/plotsummary
-------------------- Scraping faculty url 20/93 --------------------
https://www.imdb.com/title/tt0117535/plotsummary
-------------------- Scraping faculty url 21/93 --------------------
https://www.imdb.com/title/tt6368164/plotsummary
-------------------- Scraping faculty url 22/93 --------------------
https://www.imdb.com/title/tt11260832/plotsummary
-------------------- Scraping faculty url 23/93 --------------------
https://www.imdb.com/title/tt7770126/plotsummary
-------------------- Scraping faculty url 24/93 --------------------
https://www.imdb.com/title/tt1320080/plotsummary
-------------------- Scraping faculty url 25/93 --------------------
https://www.imdb.com/title/tt1470790/plotsummary
-------------------- Scraping faculty url 26/93 --------------------
https://www.imdb.com/title/tt1791829/plotsummary
-------------------- Scraping faculty url 27/93 --------------------
https://www.imdb.com/title/tt8141256/plotsummary
-------------------- Scraping faculty url 28/93 --------------------
https://www.imdb.com/title/tt6479648/plotsummary
-------------------- Scraping faculty url 29/93 --------------------
https://www.imdb.com/title/tt2127538/plotsummary
-------------------- Scraping faculty url 30/93 --------------------
https://www.imdb.com/title/tt11193390/plotsummary
-------------------- Scraping faculty url 31/93 --------------------
https://www.imdb.com/title/tt2041356/plotsummary
-------------------- Scraping faculty url 32/93 --------------------
https://www.imdb.com/title/tt1747437/plotsummary
-------------------- Scraping faculty url 33/93 --------------------
https://www.imdb.com/title/tt5004776/plotsummary
-------------------- Scraping faculty url 34/93 --------------------
https://www.imdb.com/title/tt13498286/plotsummary
-------------------- Scraping faculty url 35/93 --------------------
https://www.imdb.com/title/tt1512228/plotsummary
-------------------- Scraping faculty url 36/93 --------------------
https://www.imdb.com/title/tt6808334/plotsummary
-------------------- Scraping faculty url 37/93 --------------------
https://www.imdb.com/title/tt4077768/plotsummary
-------------------- Scraping faculty url 38/93 --------------------
https://www.imdb.com/title/tt12339486/plotsummary
-------------------- Scraping faculty url 39/93 --------------------
https://www.imdb.com/title/tt8526830/plotsummary
-------------------- Scraping faculty url 40/93 --------------------
https://www.imdb.com/title/tt5292988/plotsummary
-------------------- Scraping faculty url 41/93 --------------------
https://www.imdb.com/title/tt1754696/plotsummary
-------------------- Scraping faculty url 42/93 --------------------
https://www.imdb.com/title/tt1305897/plotsummary
-------------------- Scraping faculty url 43/93 --------------------
https://www.imdb.com/title/tt5940434/plotsummary
-------------------- Scraping faculty url 44/93 --------------------
https://www.imdb.com/title/tt10633130/plotsummary
-------------------- Scraping faculty url 45/93 --------------------
https://www.imdb.com/title/tt1535110/plotsummary
-------------------- Scraping faculty url 46/93 --------------------
https://www.imdb.com/title/tt10025484/plotsummary
-------------------- Scraping faculty url 47/93 --------------------
https://www.imdb.com/title/tt0467490/plotsummary
-------------------- Scraping faculty url 48/93 --------------------
https://www.imdb.com/title/tt0159876/plotsummary
-------------------- Scraping faculty url 49/93 --------------------
https://www.imdb.com/title/tt12885984/plotsummary
-------------------- Scraping faculty url 50/93 --------------------
https://www.imdb.com/title/tt2523718/plotsummary
-------------------- Scraping faculty url 51/93 --------------------
https://www.imdb.com/title/tt4692922/plotsummary
-------------------- Scraping faculty url 52/93 --------------------
https://www.imdb.com/title/tt5668346/plotsummary
-------------------- Scraping faculty url 53/93 --------------------
https://www.imdb.com/title/tt3563926/plotsummary
-------------------- Scraping faculty url 54/93 --------------------
https://www.imdb.com/title/tt4507312/plotsummary
-------------------- Scraping faculty url 55/93 --------------------
https://www.imdb.com/title/tt2162743/plotsummary
-------------------- Scraping faculty url 56/93 --------------------
https://www.imdb.com/title/tt0115588/plotsummary
-------------------- Scraping faculty url 57/93 --------------------
https://www.imdb.com/title/tt11221694/plotsummary
-------------------- Scraping faculty url 58/93 --------------------
https://www.imdb.com/title/tt7842852/plotsummary
-------------------- Scraping faculty url 59/93 --------------------
https://www.imdb.com/title/tt10935926/plotsummary
-------------------- Scraping faculty url 60/93 --------------------
https://www.imdb.com/title/tt7174612/plotsummary
-------------------- Scraping faculty url 61/93 --------------------
https://www.imdb.com/title/tt15692286/plotsummary
-------------------- Scraping faculty url 62/93 --------------------
https://www.imdb.com/title/tt1696526/plotsummary
-------------------- Scraping faculty url 63/93 --------------------
https://www.imdb.com/title/tt1596733/plotsummary
-------------------- Scraping faculty url 64/93 --------------------
https://www.imdb.com/title/tt13773882/plotsummary
-------------------- Scraping faculty url 65/93 --------------------
https://www.imdb.com/title/tt0902733/plotsummary
-------------------- Scraping faculty url 66/93 --------------------
https://www.imdb.com/title/tt5738656/plotsummary
-------------------- Scraping faculty url 67/93 --------------------
https://www.imdb.com/title/tt10613086/plotsummary
-------------------- Scraping faculty url 68/93 --------------------
https://www.imdb.com/title/tt1780931/plotsummary
-------------------- Scraping faculty url 69/93 --------------------
https://www.imdb.com/title/tt0101518/plotsummary
-------------------- Scraping faculty url 70/93 --------------------
https://www.imdb.com/title/tt1024861/plotsummary

-------------------- Scraping faculty url 71/93 --------------------
https://www.imdb.com/title/tt12339478/plotsummary
-------------------- Scraping faculty url 72/93 --------------------
https://www.imdb.com/title/tt5257628/plotsummary
-------------------- Scraping faculty url 73/93 --------------------
https://www.imdb.com/title/tt4490348/plotsummary
-------------------- Scraping faculty url 74/93 --------------------
https://www.imdb.com/title/tt8374098/plotsummary
-------------------- Scraping faculty url 75/93 --------------------
https://www.imdb.com/title/tt8374136/plotsummary
-------------------- Scraping faculty url 76/93 --------------------
https://www.imdb.com/title/tt11050872/plotsummary
-------------------- Scraping faculty url 77/93 --------------------
https://www.imdb.com/title/tt1238715/plotsummary
-------------------- Scraping faculty url 78/93 --------------------
https://www.imdb.com/title/tt10736066/plotsummary
-------------------- Scraping faculty url 79/93 --------------------
https://www.imdb.com/title/tt11537730/plotsummary
-------------------- Scraping faculty url 80/93 --------------------
https://www.imdb.com/title/tt5108524/plotsummary
-------------------- Scraping faculty url 81/93 --------------------
https://www.imdb.com/title/tt3531988/plotsummary
-------------------- Scraping faculty url 82/93 --------------------
https://www.imdb.com/title/tt10691474/plotsummary
-------------------- Scraping faculty url 83/93 --------------------
https://www.imdb.com/title/tt2951478/plotsummary
-------------------- Scraping faculty url 84/93 --------------------
https://www.imdb.com/title/tt11323320/plotsummary
-------------------- Scraping faculty url 85/93 --------------------
https://www.imdb.com/title/tt0442806/plotsummary
-------------------- Scraping faculty url 86/93 --------------------
https://www.imdb.com/title/tt10360064/plotsummary
-------------------- Scraping faculty url 87/93 --------------------
https://www.imdb.com/title/tt2226376/plotsummary
-------------------- Scraping faculty url 88/93 --------------------
https://www.imdb.com/title/tt8130558/plotsummary
-------------------- Scraping faculty url 89/93 --------------------
https://www.imdb.com/title/tt1682973/plotsummary
-------------------- Scraping faculty url 90/93 --------------------
https://www.imdb.com/title/tt10084900/plotsummary
-------------------- Scraping faculty url 91/93 --------------------
https://www.imdb.com/title/tt0462149/plotsummary
-------------------- Scraping faculty url 92/93 --------------------
https://www.imdb.com/title/tt1748051/plotsummary
-------------------- Scraping faculty url 93/93 --------------------
https://www.imdb.com/title/tt0437984/plotsummary

In [ ]:
titles=pd.read_csv('titles.csv')
titles = titles[['tconst','primaryTitle']]
titles.to_csv('titles.csv',header=True,index=False)
titlesdict = dict(zip(titles.tconst, titles.primaryTitle))

In [22]:
actors['movieNames']=''
for i in range(len(actors)):
    fl_1 = actors['nconst'][i]
    movieNames = ''
    dataAct=actors['primaryName'][i]+':\n'
    for fl_2 in actors['knownForTitles'][i].split(','):
        movieNames = movieNames+
        fl_2 = '/Users/apillai2/000_CS410_PROJECT/movieFile/'+fl_2+'.txt'
        with open(fl_2, 'r') as file:
            data = file.read().replace('\n \n', '')
            dataAct = dataAct+'\n'+data
    act_file = '/Users/apillai2/000_CS410_PROJECT/actorFile/'+fl_1+'.txt'
    actors['movieNames'][i] = movieNames
    write_lst(dataAct,act_file)

<ipython-input-22-6a42944781a5>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  actors['movieNames'][i] = movieNames

In [23]:
#actors.to_csv('actors.csv',header=True,index=False)
actors.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles,titleCount,movieNames
0,nm0244191,Peter Durkin,\N,\N,"actor,stunts","tt10360064,tt2951478,tt0159876,tt0179846,tt010...",5,[]
1,nm0300543,Per Gade,\N,\N,"music_department,actor","tt2127538,tt0115588,tt0467490,tt1111774,tt0115374",5,[]
2,nm0472407,Dora Krsková,1978,\N,actress,"tt7174612,tt1024861,tt0356799,tt6368164,tt0117...",6,[]
3,nm10102449,Zachary Iziah Smith,1991,\N,"actor,composer,writer","tt15445360,tt14726796,tt10633130,tt10691474,tt...",5,[]
4,nm10163074,Monika Tyagi,\N,\N,"assistant_director,actress","tt15692286,tt8130558,tt11260832,tt13773882,tt8...",5,[]
5,nm10574105,Dylan Beiler,\N,\N,actor,"tt12885984,tt10613086,tt11620836,tt10935926,tt...",5,[]
6,nm1827550,Gina Novotchin,\N,\N,"make_up_department,actress","tt1682973,tt1238715,tt1754696,tt0832445,tt0437984",5,[]
7,nm1858039,Meelis Muhu,\N,\N,"actor,producer,director","tt0462149,tt2523718,tt7770126,tt10741606,tt044...",5,[]
8,nm2453959,Adam Digby,\N,\N,"producer,actor","tt0902733,tt6808334,tt1470790,tt4692922,tt8141256",5,[]
9,nm3480395,Stu Turner,\N,\N,"actor,producer","tt2090537,tt2041356,tt2162743,tt2280364,tt5257...",6,[]
10,nm3528700,Mia Perovetz,\N,\N,actress,"tt1748051,tt1512228,tt1596733,tt1320080,tt1535110",5,[]
11,nm4009001,Chantel Harpole,\N,\N,"actress,director,producer","tt3563926,tt11323320,tt3531988,tt2226376,tt169...",5,[]
12,nm6083431,Tawan Sanders,\N,\N,"director,actress,art_department","tt11221694,tt10084900,tt5004776,tt5668346,tt11...",5,[]
13,nm6303770,Elsa de Alfonso,\N,\N,"actress,composer,sound_department","tt1305897,tt5738656,tt4077768,tt10736066,tt411...",5,[]
14,nm7004876,Elijah Evans IV,\N,\N,actor,"tt12339486,tt11050872,tt1747437,tt4507312,tt12...",5,[]
15,nm7649622,Matthew Delia,\N,\N,"actor,director,writer","tt5108524,tt6661466,tt5292988,tt7525558,tt4490348",5,[]
16,nm7669747,Erin Kiniry,\N,\N,"actress,producer","tt5940434,tt7842852,tt13498286,tt5132628,tt115...",5,[]
17,nm8745061,Ben Kawaller,\N,\N,"actor,writer","tt6479648,tt8374098,tt8374136,tt8526830,tt6915926",5,[]